[package]
name = "pseudo-csv"
version = "0.1.0"
edition = "2018"


[dependencies]
csv = "1.1"
base64 = "0.13"
block-modes = "0.8.1"
aes = "0.7.4"
cached = "0.23.0"
rayon = "1.1"
hkdf = "0.11.0"
sha2 = "0.9.5"

