[package]
name = "pseudo-csv"
version = "1.0.0"
edition = "2018"


[dependencies]
aes = "0.7.4"
base64 = "0.13"
block-modes = "0.8.1"
cached = "0.23.0"
clap = "2.33"
csv = "1.1"
hkdf = "0.11.0"
rayon = "1.1"
serde = "1"
sha2 = "0.9.5"
